### ISSUE TITLE
[S2 - PBI10] Membuat fitur untuk bantuan Lupa Password

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#10]
Sebagai Peternak dan User Registered, Saya bisa saja lupa password sehingga password bisa di reset dan saya dapat login kembali

**Comment by ennmatien** [comment]
Berikut merupakan Usecase Description, Activity Diagram & Mockup Terkait :

Usecase Description :
![image](https://user-images.githubusercontent.com/91744496/164177837-3dec9f25-aec8-4a77-99dd-6ac99b00ed17.png)


Activity Diagram :
![Activity diagram RPL-Page-15 (1)](https://user-images.githubusercontent.com/91744496/164178210-adf7eca7-1508-4d0d-a73a-b2e662ae84ac.png)


Mockup :

![Forgot-Password 1-Page](https://user-images.githubusercontent.com/91744496/164178374-d3ce05b8-5bac-4976-9cce-1ea27c6988d8.png)
![Forgot-Password 2-Page](https://user-images.githubusercontent.com/91744496/164178388-25b561c1-321a-4945-8310-82ad4c108c99.png)
![Forgot-Password 3-Page](https://user-images.githubusercontent.com/91744496/164178393-77bf0b4c-3cfd-4783-b9e2-5af952a1e2f5.png)
![Forgot-Password-Page](https://user-images.githubusercontent.com/91744496/164178401-6b8158fd-47f6-485f-b0fa-76ecac428230.png)

**Comment by fajribryan** [comment]
Hasil Video Demo PBI 10

https://user-images.githubusercontent.com/92259316/170612027-4c299f8e-3c63-4d44-bd00-ff1a06f147d3.mp4
