### ISSUE TITLE
[S3 - PBI11] Membuat Laman Kumpulan Produk

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#11]
Sebagai User, Saya dapat melihat/mencari produk-produk yang terdaftar pada website.

**Comment by brianajaaa** [comment]
>>berikut adalah use case scenario dari kumpulan produk
![image](https://user-images.githubusercontent.com/92225948/171597638-33c65318-6e09-4a4c-9192-a2a007651687.png)

>>berikut adalah activity diagram dari kumpulan produk
![browsing produk](https://user-images.githubusercontent.com/92225948/171625813-246bf479-4cfd-466f-b96b-a58ab58d76a8.jpg)

>>Mockup Kumpulan Produk
![Kumpulan produk](https://user-images.githubusercontent.com/92225948/171631226-4192e4bd-465a-40a1-813f-ebcda05bbd8c.png)

>>mockup kumpulan produk dengan filter
![Kumpulan produk (1)](https://user-images.githubusercontent.com/92225948/171631317-a66b206c-45a3-4ffb-8687-3f1a37204853.png)

**Comment by ennmatien** [comment]
https://user-images.githubusercontent.com/91744496/174992535-34822d3c-9205-4401-8b80-134d9ff3c019.mp4
