### ISSUE TITLE
[S3 - PBI13] Membuat fitur buku akuntan

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#13]
Sebagai Peternak, Saya dapat melihat cash flow sehingga saya tahu transaksi apa saja yang sudah terjadi

**Comment by dzzlr** [comment]
# Use Case Description
## Use Case Access Journal Accountant
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Access Transaction Journal Accountant |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil melihat informasi pendapatan |
| **Trigger** | Farmer ingin melihat history data pendapatan/pengeluaran |
| **Main Flow** | 1. Farmer mengakses tab 'Buku Akuntran' pada navigasi sidebar Dashboard<br/>2. Farmer mengakses buku income/outcome<br/>3. Farmer melihat history data pendapatan berdasarkan data |
| **Alternative Flow** | Alert dari sistem tidak bisa menambah jurnal |

## Use Case Create Journal Accountant
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Create Transaction Journal Accountant |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menambahkan sebuah transaksi |
| **Trigger** | Farmer ingin menambah data pendapatan/pengeluaran |
| **Main Flow** | 1. Farmer mengakses tab 'Buku Akuntran' pada navigasi sidebar Dashboard<br/>2. Farmer mengakses buku income/outcome<br/>3. Farmer mengisi form untuk menuliskan pendapatan/outcome<br/>4. Farmer mengirim/submit form Buku Akuntan<br/>5. Farmer berhasil menambah transaksi |
| **Alternative Flow** | Alert dari sistem tidak bisa menambah jurnal |

## Use Case Delete Journal Accountant
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Delete Transaction Journal Accountant |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menghapus sebuah transaksi |
| **Trigger** | Farmer ingin menghapus data pendapatan/pengeluaran |
| **Main Flow** | 1. Farmer mengakses tab 'Buku Akuntran' pada navigasi sidebar Dashboard<br/>2. Farmer mengakses buku income/outcome<br/>3. Farmer menentukan salah satu transaksi yang ingin dihapus<br/>4. Farmer menghapus transaksi pendapatan dengan mengklik tombol 'delete' pada kolom aksi<br/>5. Farmer berhasil menghapus transaksi |
| **Alternative Flow** | Alert dari sistem tidak bisa menghapus jurnal |

<hr/>

# Activity Diagram
![image](https://user-images.githubusercontent.com/87844859/170304740-55058d79-6e39-4600-af3a-a0c94ff14999.png)

<hr/>

# Mockup
![Jurnal-Page](https://user-images.githubusercontent.com/87844859/171767513-1915d572-4b0a-4aac-a646-b7dae5ec4286.png)

**Comment by dzzlr** [comment]
# Video Hasil PBI13
https://user-images.githubusercontent.com/87844859/174914933-a97073d5-acbb-4bc2-8872-b427c6dd07ef.mp4
