### ISSUE TITLE
[S3 - PBI14] Membuat fitur untuk Melihat dan Update Profile

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#14]
Sebagai Peternak dan User Registered, Saya dapat mengubah profil sesuai yang diinginkan oleh saya

**Comment by fajribryan** [comment]
![image](https://user-images.githubusercontent.com/92259316/171639618-0698b6e3-f1b4-40ba-857d-f2c2dedbfb35.png)

Berikut Usecase Diagram

**Comment by fajribryan** [comment]
![image](https://user-images.githubusercontent.com/92259316/171640253-90ea4c95-ec2a-4abf-8f57-ddde7d62e872.png)

Usecase Scenario

**Comment by fajribryan** [comment]
![Melihat Profile](https://user-images.githubusercontent.com/92259316/171640508-46f38ffe-e477-4fb7-aadc-bbbd498f6f34.png)

mockup melihat profile

**Comment by fajribryan** [comment]
![Ubah Profile](https://user-images.githubusercontent.com/92259316/171640648-7d65db13-44d0-4fcf-ab6b-593636e6d535.png)

Edit profile

**Comment by fajribryan** [comment]
Uploading 2022-06-22 16-04-22.mp4…
Video Hasil PBI-14

**Comment by fajribryan** [comment]
https://user-images.githubusercontent.com/92259316/174991139-d6a6bb23-5627-4d39-a301-c2115957c8ed.mp4

Video Hasil PBI-14
