### ISSUE TITLE
[S3 - PBI15] Membuat fitur untuk memberikan review kepada vendor

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#15]
Sebagai Peternak dan User Registered, Saya bisa menilai vendor yang menyediakan produk dari proses bisnis penjualan mereka

**Comment by icarryu** [comment]
# Use Case Description
## Use Case Review Toko
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Review Toko |
| **Use Case ID** | R4 |
| **Actor** | Registered User |
| **Include** | - |
| **Pre-Condition** | Sudah membuat akun|
| **Post-Condition** | Toko telah di-review |
| **Trigger** | - |
| **Main Flow** | 1. User Registered mengakses tab toko<br/>2. User Registered melihat toko<br/>3. User Registered klik tambahkan review toko<br/>4. User Registered melakukan pengisian form review<br/>5. User Registered submit hasil review<br/> |
| **Alternative Flow** | - |

<hr/>

# Activity Diagram
![image](https://user-images.githubusercontent.com/91745740/170191524-856537af-2de0-4ce2-9a4d-e570fedb29ce.png)


<hr/>

# Mockup
## Pertama
![image](https://user-images.githubusercontent.com/91745740/171576927-77d02f5c-a758-4fd2-99e3-04261962898e.png)

## Kedua
![image](https://user-images.githubusercontent.com/91745740/171577108-b9e11477-60ff-4453-8100-663213d7e2b0.png)

## Ketiga
![image](https://user-images.githubusercontent.com/91745740/171577150-cfb18106-383e-4bae-b054-b1b4e6c240fa.png)

**Comment by icarryu** [comment]
Video Hasil PBI-15


https://user-images.githubusercontent.com/91745740/174949582-ef3cc9ec-bb36-4095-a57a-df7e2ac96067.mp4
