### ISSUE TITLE
[S1 - PBI2] Membuat laman Landing Page

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#2]
Sebagai Registered User, Saya bisa mengakses halaman landing page sehingga saya dapat memilih fitur yang ingin saya akses

**Comment by ennmatien** [comment]
Berikut Usecase Description, Activity Diagram & Mockup Terkait PBI ini :

Usecase Description :
![image](https://user-images.githubusercontent.com/91744496/160271498-743e7190-8762-412a-809a-0914e1280208.png)

Activity Diagram:
![Activity diagram RPL-Page-1 (1)](https://user-images.githubusercontent.com/91744496/160271510-58b23c32-edc1-4591-9ef8-b2bc0ad3128e.png)

Mockup :
![Landing-Page v1 (1)](https://user-images.githubusercontent.com/91744496/161368834-fc03c92f-fa7d-4717-9330-f60f441ec4e0.png)


**Versi 2 (User telah login)**

![Logout (1)](https://user-images.githubusercontent.com/91744496/160271568-df19d2f3-a0c0-41aa-8819-24f2556af722.png)

**Comment by ekkynovrizalam** [comment]
Tambahkan hal yang dinamis dari segi konten landing page nya. apakah bisa?

**Comment by ennmatien** [comment]
> Tambahkan hal yang dinamis dari segi konten landing page nya. apakah bisa?

Baik pak, bagaimana kalau konten landing page nya ditambah dengan section yang berisi 3 produk yang paling terbaru di daftarkan oleh vendor/peternak yang terdaftar di websitenya?
