### ISSUE TITLE
[S1 - PBI3] Mengelola Informasi Toko

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#3]
Sebagai Peternak, Saya dapat membuka Toko untuk Peternakan saya sehingga saya bisa mendapatkan keuntungan

**Comment by brianajaaa** [comment]
berikut use case scenario, activity diagram, dan mock-up terkait membuat laman toko

>use case scenario
![image](https://user-images.githubusercontent.com/92225948/161366871-136f4ce5-f2ff-402f-a4a4-5817b55a6c66.png)

![image](https://user-images.githubusercontent.com/92225948/161366898-8eb58718-d379-4664-8378-1fd9453a00b3.png)

![image](https://user-images.githubusercontent.com/92225948/161366901-59e33645-08ff-4116-8762-05bb9c1ba4dc.png)

![image](https://user-images.githubusercontent.com/92225948/161366911-3bb9c80c-de9d-4673-bf9a-2411e8142c15.png)


>activity diagram
![Activity diagram RPL-buka toko](https://user-images.githubusercontent.com/91744496/161185756-42824cce-e585-4182-870b-253b3b0f2b2e.png)

![Activity diagram RPL-lihat toko (1)](https://user-images.githubusercontent.com/91744496/161186212-ac284d70-5ac7-4538-a3ff-41bad88c4315.png)


![Activity diagram RPL-edit toko](https://user-images.githubusercontent.com/91744496/161185767-3c673399-6ac4-48f4-adb4-164287b92a7f.png)

![Activity diagram RPL-tutup toko](https://user-images.githubusercontent.com/91744496/161185931-1151c0cf-1951-4ccb-bf72-f526c027281c.png)


>mock-up
![Fitur buat laman toko](https://user-images.githubusercontent.com/92225948/160270980-172c8907-e5b3-4bc0-97bb-a0e236582d27.jpg)

![Fitur buat laman toko-1](https://user-images.githubusercontent.com/92225948/160270986-0d915d3f-6d64-4692-9e43-64ed0d6b1f4d.jpg)

![Kunjungi toko - detail toko (vendor perspective)](https://user-images.githubusercontent.com/92225948/160270989-47de9998-bdec-4492-9bb0-b9fdc4f872a4.jpg)

![Kunjungi toko - detail toko](https://user-images.githubusercontent.com/92225948/160270990-a7d6d2ab-4ed7-4422-91a6-d415e56fb6e1.jpg)

![Kunjungi toko - produk (Vendor perspective)](https://user-images.githubusercontent.com/92225948/160270992-c17fe0e2-ac46-494f-bac6-e13ef135dabc.jpg)

![Kunjungi toko](https://user-images.githubusercontent.com/92225948/160270997-5b2a262f-6ee1-433b-884e-f829bfe5fd68.jpg)

**Comment by ekkynovrizalam** [comment]
PBI ini saya terima jika selain create toko terdapat fitur untuk mengelola toko tsb, bisa update dan bisa pengajuan delete. Gmna?

**Comment by ennmatien** [comment]
> PBI ini saya terima jika selain create toko terdapat fitur untuk mengelola toko tsb, bisa update dan bisa pengajuan delete. Gmna?

Baik pak, kami targetkan untuk membuat laman toko nya full CRUD

**Comment by ennmatien** [comment]
**Berikut Mockup tambahan terkait update & delete dari laman toko :**

![Fitur buat laman toko (1)](https://user-images.githubusercontent.com/91744496/160358131-69840258-6043-4670-8eb8-3ee3a6042ab3.jpg)

![Fitur buat laman toko](https://user-images.githubusercontent.com/91744496/160358167-dff8573b-dfe1-4341-a86a-24fa219de47a.jpg)
