### ISSUE TITLE
[S1 - PBI4] Mengelola Produk di Toko

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#4]
Sebagai Peternak, Saya dapat menjual produk sehingga dapat menghasilkan keuntungan dalam penjualan

**Comment by ennmatien** [comment]
# Use Case Description
## Use Case Add Product
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Add Product |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menambahkan Produk |
| **Trigger** | Farmer ingin menambah Produk |
| **Main Flow** | 1. Farmer mengakses tab 'Produk' pada navigasi sidebar Dashboard<br/>2. Farmer klik 'Add Product'<br/>3. Farmer mengisi form untuk Produk<br/>4. Farmer mengirim/submit form Produk<br/>5. Farmer mendapatkan alert sukses menambah produk |
| **Alternative Flow** | Alert dari sistem tidak bisa menambah produk |

<hr/>

## Use Case View Product
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Add Product |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer melihat hasil setelah menambahkan Produk |
| **Trigger** | Farmer ingin melihat hasil produk |
| **Main Flow** | 1. Farmer mengakses tab 'Produk' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data produk mana yang ingin dilihat pada kolom 'action'<br/>3. Farmer masuk pada halaman baru yang menampilkan Tampilan Detail Produknya |
| **Alternative Flow** | Alert dari sistem tidak dapat menampilkan produk |

<hr/>

## Use Case Delete Product
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Delete Product |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menghapus Produk |
| **Trigger** | Farmer ingin menghapus Produk |
| **Main Flow** | 1. Farmer mengakses tab 'Produk' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data produk mana yang ingin dihapus pada kolom 'action'<br/>3. Farmer mengkonfirmasi Produk tersebut pada modal saat mau mengahapus<br/>4. Farmer mendapatkan alert sukses menghapus produk |
| **Alternative Flow** | - |

<hr/>

## Use Case Edit Product
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Edit Product |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil Edit Produk |
| **Trigger** | Farmer ingin edit Produk |
| **Main Flow** | 1. Farmer mengakses tab 'Produk' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data produk mana yang ingin diedit pada kolom 'action'<br/>3. Farmer mengisi form untuk Produk<br/>4. Farmer mengirim/submit form Produk<br/>5. Farmer mendapatkan alert sukses edit produk |
| **Alternative Flow** | Alert dari sistem tidak dapat edit produk |

<hr/>

# Activity Diagram 
![image](https://user-images.githubusercontent.com/91744496/160270706-1bf230ba-029b-4e54-a2ba-ab9bf5e0203c.png)

# Mockup
laman tambah produk
![Tambah Produk -fakhri](https://user-images.githubusercontent.com/91744496/160270880-eb5c4059-f213-4fca-bc07-d9c815bab1ef.png)

laman detail produk - vendor perspective
![Kunjungi toko - detail produk v2](https://user-images.githubusercontent.com/91744496/160270898-3fc3d14f-96fa-42a9-ac07-52752356fe7a.png)

laman detail produk 
![Kunjungi toko - detail produk v2 (1)](https://user-images.githubusercontent.com/91744496/160270915-4f7f5bac-98f4-4ce3-b805-369d728c972f.png)

**Comment by ekkynovrizalam** [comment]
PBI ini saya terima jika proses ini bisa dikelola datanya oleh pendaftar. Bisa di CRUD. gmna?

**Comment by ennmatien** [comment]
> PBI ini saya terima jika proses ini bisa dikelola datanya oleh pendaftar. Bisa di CRUD. gmna?

Siap pak, di mockupnya sudah meliputi CRU, dan akan kami tambahkan agar pengelolaannya data produknya full CRUD

**Comment by ennmatien** [comment]
**Berikut Mockup tambahan terkait dengan update & delete dari pengelolaan produk :**

![Tambah Produk -fakhri (1)](https://user-images.githubusercontent.com/91744496/160358991-effeff3e-a0b6-4d8a-894b-23eeb8d946ee.png)

![Tambah Produk -fakhri (2)](https://user-images.githubusercontent.com/91744496/160359020-8204ab8f-7b4d-4172-a61c-58e0420dd0ad.png)
