### ISSUE TITLE
[S1 - PBI5] Membuat laman kumpulan toko yang terdaftar

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#5]
Sebagai User Registered, Saya bisa melihat & mengakses toko dari list toko-toko yang terdaftar pada website

**Comment by ennmatien** [comment]
Berikut Usecase Description, Activity Diagram & Mockup terkait PBI ini :

Usecase Description : 
![image](https://user-images.githubusercontent.com/91744496/160271135-f5128425-607d-4455-bd3b-2a102debedf7.png)

Activity Diagram :
![image](https://user-images.githubusercontent.com/91744496/160271136-966ae223-8dff-435e-bc97-cee92f1f410b.png)

Mockup :
![Toko-Page](https://user-images.githubusercontent.com/91744496/160271162-0d2443c1-2372-45b0-878b-142ff95391ab.png)

**Comment by ekkynovrizalam** [comment]
ini user story dan requirement nya memang gk sync ya?

**Comment by ennmatien** [comment]
> ini user story dan requirement nya memang gk sync ya?

oiya pak maaf, untuk user storynya ada kekeliruan, sudah saya update kembali pak

**Comment by ekkynovrizalam** [comment]
ditambahkan filter dan search
