### ISSUE TITLE
[S2 - PBI6] Membuat laman blog & news

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#6]
Sebagai Guest & User, Saya dapat mendapatkan informasi edukatif terkait peternakan sehingga membuka wawasan terkait peternakan bagi saya

**Comment by brianajaaa** [comment]
Use Case:
![image](https://user-images.githubusercontent.com/92225948/164178706-9a9a5a39-1bfc-43c4-a886-6e15580964b2.png)

Activity Diagram:
![Untitled](https://user-images.githubusercontent.com/92225948/164179120-245b27fb-c641-458c-acf3-d8c15e78fbcd.jpg)

MockUp:
![Blog-Page](https://user-images.githubusercontent.com/92225948/164183079-04fcba0a-eec8-4baf-8590-7df4e6db3fc2.png)


![Blog-Page (2)](https://user-images.githubusercontent.com/92225948/164183399-38f24530-ec50-4d0b-be05-4d04dc5e59eb.png)

**Comment by ekkynovrizalam** [comment]
bisa filter dan search

**Comment by brianajaaa** [comment]
demo pbi6:

https://user-images.githubusercontent.com/92225948/170611140-964b7050-6534-4248-9b24-62686e47d36f.mp4
