### ISSUE TITLE
[S2 - PBI7] Membuat fitur untuk mengelola tulisan di blog

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#7]
Sebagai Peternak, Saya bisa menuliskan & Mengelola blog sehingga saya bisa membagikan informasi yang bermanfaat

**Comment by dzzlr** [comment]
# Use Case Description
## Use Case Add Blog Post
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Add Blog Post |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menambahkan Blog Post |
| **Trigger** | Farmer ingin menambah Post untuk di Blog |
| **Main Flow** | 1. Farmer mengakses tab 'Blog' pada navigasi sidebar Dashboard<br/>2. Farmer klik 'Add Blog'<br/>3. Farmer mengisi form untuk Blog<br/>4. Farmer mengirim/submit form Blog Post<br/>5. Farmer mendapatkan alert sukses menambah blog |
| **Alternative Flow** | Alert dari sistem tidak bisa menambah blog |

<hr/>

## Use Case View Blog Post
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | View Blog Post |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer melihat hasil setelah menambahkan Blog Post |
| **Trigger** | Farmer ingin melihat hasil Blog Post |
| **Main Flow** | 1. Farmer mengakses tab 'Post' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data blog post mana yang ingin dilihat pada kolom 'action'<br/>3. Farmer masuk pada halaman baru yang menampilkan Tampilan Blog Post |
| **Alternative Flow** | Alert dari sistem tidak dapat menampilkan Blog Post |

<hr/>

## Use Case Delete Blog
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Delete Blog Post |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil menghapus Blog Post |
| **Trigger** | Farmer ingin menghapus Blog Post |
| **Main Flow** | 1. Farmer mengakses tab 'Blog' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data Blog mana yang ingin dihapus pada kolom 'action'<br/>3. Farmer mengkonfirmasi Blog tersebut pada modal saat mau menghapus<br/>4. Farmer mendapatkan alert sukses menghapus Blog Post |
| **Alternative Flow** | - |

<hr/>

## Use Case Edit Blog Post
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Edit Blog Post |
| **Use Case ID** | F0 |
| **Actor** | Farmer |
| **Include** | - |
| **Pre-Condition** | Farmer berada pada halaman Dashboard |
| **Post-Condition** | Farmer telah berhasil Edit Blog Post |
| **Trigger** | Farmer ingin edit Blog Post |
| **Main Flow** | 1. Farmer mengakses tab 'Blog' pada navigasi sidebar Dashboard<br/>2. Farmer dapat memilih data Blog Post mana yang ingin diedit pada kolom 'action'<br/>3. Farmer mengisi form untuk Blog<br/>4. Farmer mengirim/submit form Blog<br/>5. Farmer mendapatkan alert sukses edit Blog Post |
| **Alternative Flow** | Alert dari sistem tidak dapat edit Blog Post |

<hr/>

# Activity Diagram
![image](https://user-images.githubusercontent.com/87844859/164150208-83704c16-a081-4a3d-b4c3-b3df9c6681a5.png)

<hr/>

# Mockup

## Halaman Create dan Edit
![Create-Blog-Page](https://user-images.githubusercontent.com/87844859/164459413-088b6651-2702-4a7c-aa3f-cd92d23f656c.png)

## Halaman Show 
![Detail-Blog-Page](https://user-images.githubusercontent.com/87844859/164459461-5d2ca497-1a5f-4b70-8921-7b30f84032c1.png)

**Comment by dzzlr** [comment]
# Video Hasil PBI7

https://user-images.githubusercontent.com/87844859/170612944-b518cd0f-93d3-4586-a159-42722a0f0022.mp4
