### ISSUE TITLE
[S2 - PBI8] Membuat fitur untuk melakukan pembelian produk

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#8]
Sebagai User Registered, Saya ingin membeli produk sehingga saya bisa mendapatkan produknya

**Comment by icarryu** [comment]
# Use Case Description
## Use Case Buy Product
| **Use Case** | Value |
| :--- | :--- |
| **Use Case Name** | Membeli Produk |
| **Use Case ID** | R3 |
| **Actor** | Registered |
| **Include** | - |
| **Pre-Condition** | Sudah melakukan login |
| **Post-Condition** | Registered User telah berhasil melakukan pembelian |
| **Trigger** | - |
| **Main Flow** | 1. User Registered membuka tab produk<br/>2. User Registered memilih produk<br/>3. User Registered membeli produk<br/> |
| **Alternative Flow** | Menghubungi peternaknya secara langsung |

<hr/>

# Activity Diagram
![image](https://user-images.githubusercontent.com/91745740/164153499-d0d0e523-4350-462a-bdde-550beff75a84.png)


<hr/>

# Mockup
## Pertama
![Pembelian produk ](https://user-images.githubusercontent.com/91745740/164153156-4f270cc8-1662-4751-885d-0ae48cfa7556.png)

<hr/>

## Kedua
![Pembelian produk -v2](https://user-images.githubusercontent.com/91745740/164153168-91c86452-f554-478e-8337-9a44c898132c.png)

<hr/>

## Ketiga
![Pembelian produk -v3 (1)](https://user-images.githubusercontent.com/91745740/164154350-dc0868b5-956b-4848-8d36-16344af93e43.png)

**Comment by ekkynovrizalam** [comment]
ditambahkan fitur untuk klik counter pada tombol yakin setelah klik tombol pesan, sehingga admin atau vendor dapat melihat berapa banyak orang yang klik produk tsb

**Comment by icarryu** [comment]
Video Hasil PBI-8

https://user-images.githubusercontent.com/91745740/170610868-921204cd-aa4c-4516-8565-5a4eecaf5c92.mp4
