### ISSUE TITLE
[S2 - PBI9] Membuat fitur untuk melakukan konsultasi kepada peternak

### ISSUE THREAD

**Issue by ennmatien** [SI-RPL-2022/SI4302_E_HIFARM#9]
Sebagai Peternak dan User Registered, Saya bisa melakukan diskusi serta konsultasi kepada peternak tentang cara mengelola peternakan

**Comment by ennmatien** [comment]
Berikut merupakan Usecase Description, Activity Diagram dan mockup terkait PBI ini :

Usecase Description :
![image](https://user-images.githubusercontent.com/91744496/164149297-52cbaca2-941f-4788-919c-f1b915eb5d3e.png)

![image](https://user-images.githubusercontent.com/91744496/164149371-5eaff251-2a73-4378-a359-4419c9673752.png)

![image](https://user-images.githubusercontent.com/91744496/164149419-f5915098-9b2e-421d-9570-23c478925baf.png)

![image](https://user-images.githubusercontent.com/91744496/164152551-f2dcc1da-dcae-4152-a523-64e8e147a35c.png)

![image](https://user-images.githubusercontent.com/91744496/164152594-51df134f-28c9-4677-b435-89fda65980b2.png)


Activity Diagram :
![Activity diagram RPL-Page-4 (3)](https://user-images.githubusercontent.com/91744496/164152737-404f4bdf-8f55-48b7-a60a-08339fb59514.png)

![Activity diagram RPL-Copy of Page-4 (3)](https://user-images.githubusercontent.com/91744496/164152765-5fc822c6-4310-46a6-a029-0d3c62b35137.png)

![Activity diagram RPL-Copy of Copy of Page-4 (2)](https://user-images.githubusercontent.com/91744496/164152800-e543f817-959f-4ac0-9f70-e98d9de0177d.png)

![Activity diagram RPL-Copy of Copy of Page-4 (3)](https://user-images.githubusercontent.com/91744496/164153471-4b5a659d-10d6-439b-b114-a3f3eb117899.png)

![Activity diagram RPL-Copy of Copy of Copy of Page-4](https://user-images.githubusercontent.com/91744496/164153439-8f5b5d40-e668-48ca-be74-167aae6ada57.png)



Mockup :
![Forum Konsultasi](https://user-images.githubusercontent.com/91744496/164155887-2caba9ac-9fa2-4886-a967-6843f3015b26.png)
![Forum Konsultasi - Detailed](https://user-images.githubusercontent.com/91744496/164155907-265f2c9c-c6da-457f-b432-7b97c58f0b19.png)
![Forum Konsultasi - Detailed (if creator)](https://user-images.githubusercontent.com/91744496/164155923-d0346320-3176-42ae-85ca-ab8fe532f170.png)
![Forum Konsultasi - Detailed (if creator)-1](https://user-images.githubusercontent.com/91744496/164155939-6dbd5d7f-b674-4a78-a666-e383fbdf8996.png)

![Forum Konsultasi-1](https://user-images.githubusercontent.com/91744496/164155970-09b1ab38-676a-48e9-ac52-ec8ba470f5dc.png)
![Forum Konsultasi-2](https://user-images.githubusercontent.com/91744496/164155975-e5212dcb-0aa5-452d-b9d7-e94cf9765749.png)
![Forum Konsultasi-3](https://user-images.githubusercontent.com/91744496/164155978-e833062b-ffdc-49ec-9c8b-d6c0956adca3.png)
![Forum Konsultasi-4](https://user-images.githubusercontent.com/91744496/164155979-0c59a238-678b-4b14-a100-bc02acebae91.png)

**Comment by ekkynovrizalam** [comment]
secara umum ada 2 crud, yaitu crud thread dan crud comment

**Comment by ennmatien** [comment]
https://user-images.githubusercontent.com/91744496/170612310-a8e85612-2a14-4ab1-a73c-ab4a1dec2522.mp4
